name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm i

            - run: npx prettier --check .
              if: ${{ matrix.node-version == '18.x' }}
            - run: npm run lint -w esbuild-kit
              if: ${{ matrix.node-version == '18.x' }}
              continue-on-error: true

            - run: npm run build -w esbuild-kit
            - run: npm run test -w esbuild-kit
              continue-on-error: true

    integration:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm i

            - run: npm run build -w @nova/ui
            # - run: npm run build-storybook -w @nova/ui
            - run: npm run build -w @nova/next-test
              continue-on-error: true
            - run: npm run build -w @nova/vite-test
            - run: npm run build -w @nova/webpack-test
