name: main

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm i
            - run: npx prettier --ignore-path .gitignore --check .

            - run: npm run build -w nova-build
            - run: npm run lint -w nova-build
            # - run: npm run test

            - run: npm run build -w @nova/ui
            - run: npm run build-storybook -w @nova/ui
            - run: npm run build -w @nova/next-test
            - run: npm run build -w @nova/vite-test
            - run: npm run build -w @nova/webpack-test
